<?php
$arrCompanyCRM = array (
  0 => 
    array (
      'id' => '0',
      'companyname' => '',
      'companyname_en' => '',
      'phone1' => '',
      'phone2' => '',
      'fax' => '',
      'mobilephone' =>  '',
      'contactperson' =>  '',
      'basiccategory' =>  '',
      'reference' =>  '',
      'area' =>  '',
      'geo_x' =>  '',
      'geo_y' =>  '',
      'address' =>  '',
      'zipcode' =>  '',
      'email' =>  '',
      'website' =>  '',
      'facebook' =>  '',
      'twitter' =>  '',
      'package' =>  '',
      'discount' =>  '',
      'price' =>  '',
      'vatzone' => '',
      'catalogueid' =>  '0',
      'expires' =>  '',
      'username' =>  '',
      'password' =>  '',
      'user' =>  '',
      'userdataentry' =>  '',
      'recalldate' =>  '',
      'recalltime' =>  '',
      'status' =>  '',
      'history' => '',
      'show_phone1' => '',
      'show_phone2' => '',
      'show_mobilephone' => '',
      'show_email' => '',
      'LinkedIn' =>  '',
      'ShortDescription' =>  '',
      'FullDescription' =>  '',
      'DeliveryDate' =>  '',
      'DeliveryTime' =>  '',
      'DeliveryNotes' =>  '',
      'subcategory' =>  '',
       'vn_keywords' =>  ''
    )
);
        
$arrCompany = array (
    'id' => '0',
    'company_name_gr' =>  '',
    'company_name_en' =>  '',
    'short_description_gr' =>  '',
    'short_description_en' =>  '',
    'full_description_gr' =>  '',
    'full_description_en' =>  '',
    'address_gr' =>  '',
    'address_en' =>  '',
    'zip_code' =>  '',
    'phone' =>  '',
    'phone2' =>  '',
    'mobile_phone' =>  '',
    'email' =>  '',
    'fax' =>  '',
    'website' =>  '',
    'facebook' =>  '',
    'twitter' =>  '',
    'linkedin' =>  '',
    'basic_category' =>  '',
    'area' =>  '',
    'geo_x' =>  '',
    'geo_y' =>  '',
    'package' =>  '',
    'expires' =>  '',
    'username' =>  '',
    'password' =>  '',
    'active' =>  '1',
    'keywords_gr' => ''
);

?>